version: '3.8'

services:

  # proxy:
  #   image: nginx:alpine
  #   container_name: p2-proxy
  #   ports:
  #     - "80:80"  
  #   volumes:
  #     - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - auth-service
  #     - user-service
  #     - video-service
  #   networks:
  #     - frontend-net
  #     - backend-net

    # on Linux, enable host.docker.internal
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend/toktik_frontend
      dockerfile: Dockerfile
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - frontend-net

  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    env_file:
      - .env   
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - backend-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-net
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-net

  websocket-service:
    build:
      context: ./Backend/WebsocketService
      dockerfile: Dockerfile
    container_name: websocket-service
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
    env_file:
      - ./Backend/WebsocketService/.env
    ports:
      # - "8092:8092"
      - "8080:8080"
    expose:
      - "8091"
    networks:
      - backend-net

  auth-service:
    build:
      context: ./Backend/Authentication
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./Backend/Authentication/.env
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - backend-net
      - frontend-net

  user-service:
    build:
      context: ./Backend/UserService
      dockerfile: Dockerfile
    container_name: user-service
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./Backend/UserService/.env
    ports:
      # - "8081:8081"
      - "8080:8080"
    expose:
      - "8081"
    networks:
      - backend-net
      - frontend-net

  video-service:
    build:
      context: ./Backend/VideoService
      dockerfile: Dockerfile
    container_name: video-service
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - postgres
    env_file:
      - ./Backend/VideoService/.env
    ports:
      # - "8090:8090"
      - "8080:8080"
    expose:
      - "8090"
    networks:
      - backend-net
      - frontend-net

  video-chunker:
    build:
      context: ./Backend/VideoChunker
      dockerfile: Dockerfile
    container_name: video-chunker
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - video-service
    env_file:
      - ./Backend/VideoChunker/.env
    expose:
      - "8092"
    networks:
      - backend-net

  video-convertor:
    build:
      context: ./Backend/VideoConvertor
      dockerfile: Dockerfile
    container_name: video-convertor
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - video-service
    env_file:
      - ./Backend/VideoConvertor/.env
    expose:
      - "8093"
    networks:
      - backend-net

  thumbnail-maker:
    build:
      context: ./Backend/ThumbnailMaker
      dockerfile: Dockerfile
    container_name: thumbnail-maker
    restart: always
    depends_on:
      - rabbitmq
      - redis
      - video-service
    env_file:
      - ./Backend/ThumbnailMaker/.env
    expose:
      - "8094"
    networks:
      - backend-net

networks:
  backend-net:
  frontend-net: 

volumes:
  postgres-data:
