apiVersion: v1
kind: Secret
metadata:
  name: p2-secret
  namespace: default
type: Opaque
stringData:
  POSTGRES_USER: dev
  POSTGRES_PASS: pass
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: dbp2
  SSL_MODE: disable
  PORT: "8080"
  JWT_SECRET: hello
  R2_ACCOUNT_ID: bbb272c68917a80beec7f62d8843b983
  R2_ACCESS_KEY_ID: e99424cd396ce54742efd8d055ef73e9
  R2_ACCESS_KEY_SECRET: ec0f0ddbc96ffbfa21f7c357bcef7fed3ac3355e07962e48fffafc98f8272c78
  BROKER_URI: amqp://guest:guest@rabbitmq:5672/
  BACKEND_URI: redis://redis:6379/0
  MACHINERY_QUEUE: machinery_tasks_queue

  REDIS_HOST_0: redis-cluster-0.redis-cluster-headless.default.svc.cluster.local
  REDIS_HOST_1: redis-cluster-1.redis-cluster-headless.default.svc.cluster.local
  REDIS_HOST_2: redis-cluster-2.redis-cluster-headless.default.svc.cluster.local
  REDIS_HOST_3: redis-cluster-3.redis-cluster-headless.default.svc.cluster.local
  REDIS_HOST_4: redis-cluster-4.redis-cluster-headless.default.svc.cluster.local
  REDIS_HOST_5: redis-cluster-5.redis-cluster-headless.default.svc.cluster.local
  REDIS_PORT: "6379"

  #For Cloud VM
  # REDIS_PASSWORD: PfiVemCQF3

  #For Local
  REDIS_PASSWORD: jidJW5qPyn
  REDIS_ADDRS: redis-cluster-0.redis-cluster-headless.default.svc.cluster.local:6379,redis-cluster-1.redis-cluster-headless.default.svc.cluster.local:6379,redis-cluster-2.redis-cluster-headless.default.svc.cluster.local:6379


