apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-server
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: wait-for-postgres
          image: alpine:3.19
          command:
            - sh
            - -c
            - |
              apk add --no-cache bind-tools netcat-openbsd
              echo "Waiting for postgres..."
              until nslookup postgres && nc -z postgres 5432; do
                echo "Waiting..."; sleep 2
              done
              echo "Postgres is up!"
      containers:
        - name: websocket-server
          image: ghcr.io/kitiphol/websocketserver:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: p2-secret
                  key: PORT
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: p2-secret
                  key: JWT_SECRET
            - name: REDIS_HOST_0
              valueFrom:
                secretKeyRef:
                  name: p2-secret
                  key: REDIS_HOST_0
            - name: REDIS_HOST_1
              valueFrom:
                secretKeyRef:
                  name: p2-secret
                  key: REDIS_HOST_1
            - name: REDIS_HOST_2
              valueFrom:
                secretKeyRef:
                  name: p2-secret
                  key: REDIS_HOST_2
            - name: REDIS_HOST_3
              valueFrom:
                secretKeyRef:
                  name: p2-secret
                  key: REDIS_HOST_3
            - name: REDIS_HOST_4
              valueFrom:
                secretKeyRef:
                  name: p2-secret
                  key: REDIS_HOST_4
            - name: REDIS_HOST_5
              valueFrom:
                secretKeyRef:
                  name: p2-secret
                  key: REDIS_HOST_5
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: p2-secret
                  key: REDIS_PORT
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: p2-secret
                  key: REDIS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-server
  namespace: default
spec:
  selector:
    app: websocket-server
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
